ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv('admission.csv')
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv('admission.csv')
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv('admission.csv')
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv('admission.csv')
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv('admission.csv')
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv('admission.csv')
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv('admission.csv')
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv('admission.csv')
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv(file_name)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv(file_name)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:root:Unable to load the CSV
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 33, in <module>
    data = pd.read_csv(file_name)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:__main__:Unable to Load CSV,Error: [Errno 2] No such file or directory: 'admission.csv'
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 34, in <module>
    data = pd.read_csv(file_name)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:__main__:Unable to Load CSV,Error: [Errno 2] No such file or directory: 'admission.csv'
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 34, in <module>
    data = pd.read_csv(file_name)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:__main__:Unable to Load CSV,Error: [Errno 2] No such file or directory: 'admission.csv'
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 34, in <module>
    data = pd.read_csv(file_name)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
ERROR:__main__:Unable to Load CSV,Error: [Errno 2] No such file or directory: 'admission.csv'
Traceback (most recent call last):
  File "/home/vijeth/Desktop/Mlflow/admission/admissionmlops.py", line 34, in <module>
    data = pd.read_csv(file_name)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/vijeth/anaconda3/envs/mlflow_1/lib/python3.9/site-packages/pandas/io/common.py", line 701, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'admission.csv'
